menu:
  home: /
  archives: /archives

# Fancybox
fancybox: true

#qrcode
qrcode: true

# Static files
vendors: vendors
css: css
js: js
img: img

google_site_verification:
google_analytics:

version: 0.1